### ISSUE TITLE
Avoid use of deprecated proto package in Go implementation

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/fabric-admin-sdk#53] opened 2022-11-11 15:21 UTC
```
Error: internal/configtxgen/encoder/encoder.go:14:2: SA1019: "github.com/golang/protobuf/proto" is deprecated: Use the "google.golang.org/protobuf/proto" package instead. (staticcheck)
	"github.com/golang/protobuf/proto"
```

**Comment by bestbeforetoday** [comment] 2022-11-11 16:57
This looks like a duplicate of #45

**Closed** 2022-11-12 04:02 UTC
